version: "2"

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - ineffassign
    - gocyclo
    - gosec
    - dupl
    - errcheck
    - unused
    - goconst
    - gocritic
  settings:
    dupl:
      threshold: 120
    gocyclo:
      min-complexity: 15

run:
  timeout: 30s
