tools:
  gcc:
    image: gcc:latest
    entry: gcc
    workdir: /work
    volumes:
      - $(pwd):/work

  python:
    image: python:latest
    entry: python
    workdir: /work
    volumes:
      - $(pwd):/work

  node:
    image: node:latest
    entry: node
    workdir: /work
    volumes:
      - $(pwd):/work

  rust:
    image: rust:latest
    entry: rustc
    workdir: /work
    volumes:
      - $(pwd):/work
