tools:
  hello:
    image: hello-world
    entry: /hello
    workdir: /work
    volumes:
      - $(pwd):/work

  gcc:
    image: gcc
    entry: gcc
    workdir: /work
    volumes:
      - $(pwd):/work

  python:
    image: python
    entry: python
    workdir: /work
    volumes:
      - $(pwd):/work

  node:
    image: node
    entry: node
    workdir: /work
    volumes:
      - $(pwd):/work

  rustc:
    image: rust
    entry: rustc
    workdir: /work
    volumes:
      - $(pwd):/work
